/*
 The MIT license.
 @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com>
*/
this.io={version:"0.2.4",setPath:function(a){this.path=/\/$/.test(a)?a:a+"/";if("WebSocket"in window)WebSocket.__swfLocation=a+"lib/vendor/web-socket-js/WebSocketMain.swf"}};if("jQuery"in this)jQuery.io=this.io;io.util={};
(function(){var a=io.util.Object={clone:function(c){var e;if(c instanceof Array){e=[];for(var g=0;g<c.length;g++)e[g]=a.clone(c[g]);return e}else if(typeof c=="object"){e={};for(g in a)e[g]=a.clone(a[g]);return e}else return c},merge:function(c,e,g){if(typeof e=="string")return b(c,e,g);for(var i=1,t=arguments.length;i<t;i++){var w=arguments[i];for(var n in w)b(c,n,w[n])}return c}},b=function(c,e,g){if(g instanceof Array)c[e]=a.clone(g);else if(typeof g=="object")if(typeof c[e]=="object")a.merge(c[e],
g);else c[e]=a.clone(g);else c[e]=g;return c}})();(function(){var a=io.util.Array={include:function(b,c){a.contains(b,c)||b.push(c);return b},each:function(b,c,e){for(var g=0,i=b.length;g<i;g++)c.call(e,b[g],g,b)},contains:function(b,c,e){return a.indexOf(b,c,e)!=-1},indexOf:function(b,c,e){var g=b.length;for(e=e<0?Math.max(0,g+e):e||0;e<g;e++)if(b[e]===c)return e;return-1}}})();
io.util.Options={options:{},setOption:function(a,b){io.util.Object.merge(this.options,a,b);return this},setOptions:function(a){for(var b in a)this.setOption(b,a[b]);if(this.addEvent)for(var c in this.options){if(!/^on[A-Z]/.test(c)||typeof this.options[c]!="function")return;this.addEvent(c,this.options[c]);this.options[c]=null}return this}};
io.util.Events=function(){var a=io.util.Array,b=function(e,g){g=g.replace(/^on([A-Z])/,function(t,w){return w.toLowerCase()});var i=e.$events;return i[g]||(i[g]=[])},c=function(e,g){a.each(b(e,g),function(i){e.removeEvent(g,i)})};return{$events:{},addEvent:function(e,g){a.include(b(this,e),g);return this},addEvents:function(e){for(var g in e)this.addEvent(g,e[g]);return this},fireEvent:function(e,g){g=[].concat(g);a.each(b(this,e),function(i){i.apply(this,g)},this);return this},fireEvents:function(){for(var e=
0;e<arguments.length;e++)this.fireEvent(arguments[e]);return this},removeEvent:function(e,g){var i=b(this,e),t=i.indexOf(g);t!=-1&&i.splice(t,1);return this},removeEvents:function(e){if(e===null){e=this.$events;for(var g in e)c(this,g)}else switch(typeof e){case "string":c(this,e);break;case "object":for(var i in e)this.removeEvent(i,e[i]);break}return this}}}();if(!this.JSON)this.JSON={};
(function(){function a(j){return j<10?"0"+j:j}function b(j){g.lastIndex=0;return g.test(j)?'"'+j.replace(g,function(p){var u=w[p];return typeof u==="string"?u:"\\u"+("0000"+p.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+j+'"'}function c(j,p){var u,v,B,D,C=i,y,s=p[j];if(s&&typeof s==="object"&&typeof s.toJSON==="function")s=s.toJSON(j);if(typeof n==="function")s=n.call(p,j,s);switch(typeof s){case "string":return b(s);case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);
case "object":if(!s)return"null";i+=t;y=[];if(Object.prototype.toString.apply(s)==="[object Array]"){D=s.length;for(u=0;u<D;u+=1)y[u]=c(u,s)||"null";B=y.length===0?"[]":i?"[\n"+i+y.join(",\n"+i)+"\n"+C+"]":"["+y.join(",")+"]";i=C;return B}if(n&&typeof n==="object"){D=n.length;for(u=0;u<D;u+=1){v=n[u];if(typeof v==="string")if(B=c(v,s))y.push(b(v)+(i?": ":":")+B)}}else for(v in s)if(Object.hasOwnProperty.call(s,v))if(B=c(v,s))y.push(b(v)+(i?": ":":")+B);B=y.length===0?"{}":i?"{\n"+i+y.join(",\n"+i)+
"\n"+C+"}":"{"+y.join(",")+"}";i=C;return B}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,t,w={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;if(typeof JSON.stringify!=="function")JSON.stringify=function(j,p,u){var v;t=i="";if(typeof u==="number")for(v=0;v<u;v+=1)t+=" ";else if(typeof u==="string")t=u;if((n=p)&&typeof p!=="function"&&(typeof p!=="object"||typeof p.length!=="number"))throw Error("JSON.stringify");return c("",
{"":j})};if(typeof JSON.parse!=="function")JSON.parse=function(j,p){function u(B,D){var C,y,s=B[D];if(s&&typeof s==="object")for(C in s)if(Object.hasOwnProperty.call(s,C)){y=u(s,C);if(y!==undefined)s[C]=y;else delete s[C]}return p.call(B,D,s)}var v;j=String(j);e.lastIndex=0;if(e.test(j))j=j.replace(e,function(B){return"\\u"+("0000"+B.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(j.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){v=eval("("+j+")");return typeof p==="function"?u({"":v},""):v}throw new SyntaxError("JSON.parse");}})();
(function(){var a=this,b=true,c=/xyz/.test(function(){})?/\b__super__\b/:/.*/;ioClass=function(e){if(this==a)return ioClass.extend(e)};ioClass.version="1.2.0";ioClass.extend=function(e){function g(){b&&this.init&&this.init.apply(this,arguments)}function i(n){for(var j in n)if(n.hasOwnProperty(j))g[j]=n[j]}var t=this.prototype;b=false;var w=new this;b=true;g.include=function(n){for(var j in n)if(j=="include")if(n[j]instanceof Array)for(var p=0,u=n[j].length;p<u;++p)g.include(n[j][p]);else g.include(n[j]);
else if(j=="extend")if(n[j]instanceof Array){p=0;for(u=n[j].length;p<u;++p)i(n[j][p])}else i(n[j]);else if(n.hasOwnProperty(j))w[j]=typeof n[j]=="function"&&typeof t[j]=="function"&&c.test(n[j])?function(v,B){return function(){this.__super__=t[v];return B.apply(this,arguments)}}(j,n[j]):n[j]};g.include(e);g.prototype=w;g.constructor=g;g.extend=arguments.callee;return g}})();
io.Transport=ioClass({include:[io.util.Events,io.util.Options],init:function(a,b){this.base=a;this.setOptions(b)},send:function(){throw Error("Missing send() implementation");},connect:function(){throw Error("Missing connect() implementation");},disconnect:function(){throw Error("Missing disconnect() implementation");},_onData:function(a){var b;if(typeof a==="string")try{b=JSON.parse(a)}catch(c){}else b=a;if(b&&b.messages){a=0;for(var e=b.messages.length;a<e;a++)this._onMessage(b.messages[a])}},_onMessage:function(a){if("sessionid"in
this)this.base._onMessage(a);else{try{var b=JSON.parse(a)}catch(c){}if(b&&b.sessionid){this.sessionid=b.sessionid;this._onConnect()}}},_onConnect:function(){this.connected=true;this.base._onConnect()},_onDisconnect:function(){if(this.connected){this.connected=false;this.base._onDisconnect()}},_prepareUrl:function(){return(this.base.options.secure?"https":"http")+"://"+this.base.host+":"+this.base.options.port+"/"+this.base.options.resource+"/"+this.type+(this.sessionid?"/"+this.sessionid:"/")}});
(function(){var a=new Function;io.Transport.XHR=io.Transport.extend({connect:function(){this._get()},send:function(c){this._sendXhr=this._request("send","POST");this._sendXhr.send("data="+encodeURIComponent(c))},disconnect:function(){if(this._xhr){this._xhr.onreadystatechange=this._xhr.onload=a;this._xhr.abort()}this._sendXhr&&this._sendXhr.abort();this._onClose();this._onDisconnect()},_request:function(c,e,g){var i=b(this.base._isXDomain());if(g)i.multipart=true;i.open(e||"GET",this._prepareUrl()+
(c?"/"+c:""));e=="POST"&&i.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=utf-8");return i}});var b=io.Transport.XHR.request=function(c){if("XDomainRequest"in window&&c)return new XDomainRequest;if("XMLHttpRequest"in window)return new XMLHttpRequest;try{return new ActiveXObject("MSXML2.XMLHTTP")}catch(e){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(g){}return false};io.Transport.XHR.check=function(){try{if(b())return true}catch(c){}return false}})();
io.Transport.websocket=io.Transport.extend({type:"websocket",connect:function(){var a=this;this.socket=new WebSocket(this._prepareUrl());this.socket.onmessage=function(b){a._onData(b.data)};this.socket.onclose=function(){a._onClose()};return this},send:function(a){this.socket.send(a);return this},disconnect:function(){this.socket.close();return this},_onClose:function(){this._onDisconnect()},_prepareUrl:function(){return(this.base.options.secure?"wss":"ws")+"://"+this.base.host+":"+this.base.options.port+
"/"+this.base.options.resource+"/"+this.type+(this.sessionid?"/"+this.sessionid:"")}});io.Transport.websocket.check=function(){return"WebSocket"in window&&!("__initialize"in WebSocket)};io.Transport.websocket.xdomainCheck=function(){return true};
io.Transport.flashsocket=io.Transport.websocket.extend({_onClose:function(){if(this.base.connected)return this.__super__();else{this.base.options.transports.splice(io.util.Array.indexOf(this.base.options.transports,"flashsocket"),1);this.base.transport=this.base.getTransport();this.base.connect()}}});
io.Transport.flashsocket.check=function(){if(!("path"in io))throw Error("The `flashsocket` transport requires that you call io.setPath() with the path to the socket.io client dir.");if("navigator"in window&&"plugins"in navigator&&navigator.plugins["Shockwave Flash"])return!!navigator.plugins["Shockwave Flash"].description;if("ActiveXObject"in window)try{return!!(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")}catch(a){}return false};
io.Transport.flashsocket.xdomainCheck=function(){return true};
io.Transport.htmlfile=io.Transport.extend({type:"htmlfile",connect:function(){var a=this;this._open();window.attachEvent("onunload",function(){a._destroy()})},_open:function(){this._doc=new ActiveXObject("htmlfile");this._doc.open();this._doc.write("<html></html>");this._doc.parentWindow.s=this;this._doc.close();var a=this._doc.createElement("div");this._doc.body.appendChild(a);this._iframe=this._doc.createElement("iframe");a.appendChild(this._iframe);this._iframe.src=this._prepareUrl()+"/"+ +new Date},
_:function(a,b){this._onData(a);var c=b.getElementsByTagName("script")[0];c.parentNode.removeChild(c)},_destroy:function(){this._iframe.src="about:blank";this._doc=null;CollectGarbage()},send:function(a){this._sendXhr=io.Transport.XHR.request();this._sendXhr.open("POST",this._prepareUrl()+"/send");this._sendXhr.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=utf-8");this._sendXhr.send("data="+encodeURIComponent(a))},disconnect:function(){this._destroy();this._sendXhr&&
this._sendXhr.abort();this._onClose();this._onDisconnect()}});io.Transport.htmlfile.check=function(){if("ActiveXObject"in window)try{new ActiveXObject("htmlfile");return io.Transport.XHR.check()}catch(a){}return false};io.Transport.htmlfile.xdomainCheck=function(){return false};
io.Transport["xhr-multipart"]=io.Transport.XHR.extend({type:"xhr-multipart",connect:function(){var a=this;this._xhr=this._request("","GET",true);this._xhr.onreadystatechange=function(){a._xhr.readyState==3&&a._onData(a._xhr.responseText)};this._xhr.send()}});io.Transport["xhr-multipart"].check=function(){return"XMLHttpRequest"in window&&"multipart"in XMLHttpRequest.prototype};io.Transport["xhr-multipart"].xdomainCheck=function(){return true};
(function(){var a=new Function;io.Transport["xhr-polling"]=io.Transport.XHR.extend({type:"xhr-polling",connect:function(){var b=this;this._xhr=this._request(+new Date,"GET");if("onload"in this._xhr)this._xhr.onload=function(){this.responseText.length&&b._onData(this.responseText);b.connect()};else this._xhr.onreadystatechange=function(){var c;if(b._xhr.readyState==4){b._xhr.onreadystatechange=a;try{c=b._xhr.status}catch(e){}if(c==200){b._xhr.responseText.length&&b._onData(b._xhr.responseText);b.connect()}}};
this._xhr.send()}});io.Transport["xhr-polling"].check=function(){return io.Transport.XHR.check()};io.Transport["xhr-polling"].xdomainCheck=function(){return"XDomainRequest"in window||"XMLHttpRequest"in window}})();
io.Socket=ioClass({include:[io.util.Events,io.util.Options],options:{secure:false,document:document,port:document.location.port||80,resource:"socket.io",transports:["websocket","flashsocket","htmlfile","xhr-multipart","xhr-polling"],transportOptions:{},rememberTransport:true},init:function(a,b){this.host=a||document.domain;this.setOptions(b);this.connecting=this.connected=false;this.transport=this.getTransport();!this.transport&&"console"in window&&console.error("No transport available")},getTransport:function(){var a=
this.options.transports,b;if(this.options.rememberTransport)if(b=this.options.document.cookie.match("(?:^|;)\\s*socket.io=([^;]*)"))a=[decodeURIComponent(b[1])];for(b=0;transport=a[b];b++)if(io.Transport[transport]&&io.Transport[transport].check()&&(!this._isXDomain()||io.Transport[transport].xdomainCheck()))return new io.Transport[transport](this,this.options.transportOptions[transport]||{});return null},connect:function(){if(this.transport&&!this.connected&&!this.connecting){this.connecting=true;
this.transport.connect()}return this},send:function(a){if(!this.transport||!this.transport.connected)return this._queue(a);this.transport.send(JSON.stringify([a]));return this},disconnect:function(){this.transport.disconnect();return this},_queue:function(a){if(!("_queueStack"in this))this._queueStack=[];this._queueStack.push(a);return this},_doQueue:function(){if(!("_queueStack"in this)||!this._queueStack.length)return this;this.transport.send(JSON.stringify([].concat(this._queueStack)));this._queueStack=
[];return this},_isXDomain:function(){return this.host!==document.domain},_onConnect:function(){this.connected=true;this.connecting=false;this._doQueue();if(this.options.rememberTransport)this.options.document.cookie="socket.io="+encodeURIComponent(this.transport.type);this.fireEvent("connect")},_onMessage:function(a){this.fireEvent("message",a)},_onDisconnect:function(){this.fireEvent("disconnect")}});
var swfobject=function(){function a(){if(!L){try{var d=o.getElementsByTagName("body")[0].appendChild(o.createElement("span"));d.parentNode.removeChild(d)}catch(f){return}L=true;d=P.length;for(var h=0;h<d;h++)P[h]()}}function b(d){if(L)d();else P[P.length]=d}function c(d){if(typeof E.addEventListener!=x)E.addEventListener("load",d,false);else if(typeof o.addEventListener!=x)o.addEventListener("load",d,false);else if(typeof E.attachEvent!=x)B(E,"onload",d);else if(typeof E.onload=="function"){var f=
E.onload;E.onload=function(){f();d()}}else E.onload=d}function e(){var d=o.getElementsByTagName("body")[0],f=o.createElement(F);f.setAttribute("type",Q);var h=d.appendChild(f);if(h){var k=0;(function(){if(typeof h.GetVariable!=x){var l=h.GetVariable("$version");if(l){l=l.split(" ")[1].split(",");m.pv=[parseInt(l[0],10),parseInt(l[1],10),parseInt(l[2],10)]}}else if(k<10){k++;setTimeout(arguments.callee,10);return}d.removeChild(f);h=null;g()})()}else g()}function g(){var d=I.length;if(d>0)for(var f=
0;f<d;f++){var h=I[f].id,k=I[f].callbackFn,l={success:false,id:h};if(m.pv[0]>0){var r=v(h);if(r)if(D(I[f].swfVersion)&&!(m.wk&&m.wk<312)){y(h,true);if(k){l.success=true;l.ref=i(h);k(l)}}else if(I[f].expressInstall&&t()){l={};l.data=I[f].expressInstall;l.width=r.getAttribute("width")||"0";l.height=r.getAttribute("height")||"0";if(r.getAttribute("class"))l.styleclass=r.getAttribute("class");if(r.getAttribute("align"))l.align=r.getAttribute("align");var q={};r=r.getElementsByTagName("param");for(var z=
r.length,A=0;A<z;A++)if(r[A].getAttribute("name").toLowerCase()!="movie")q[r[A].getAttribute("name")]=r[A].getAttribute("value");w(l,q,h,k)}else{n(r);k&&k(l)}}else{y(h,true);if(k){if((h=i(h))&&typeof h.SetVariable!=x){l.success=true;l.ref=h}k(l)}}}}function i(d){var f=null;if((d=v(d))&&d.nodeName=="OBJECT")if(typeof d.SetVariable!=x)f=d;else if(d=d.getElementsByTagName(F)[0])f=d;return f}function t(){return!R&&D("6.0.65")&&(m.win||m.mac)&&!(m.wk&&m.wk<312)}function w(d,f,h,k){R=true;X=k||null;Z={success:false,
id:h};var l=v(h);if(l){if(l.nodeName=="OBJECT"){N=j(l);S=null}else{N=l;S=h}d.id=$;if(typeof d.width==x||!/%$/.test(d.width)&&parseInt(d.width,10)<310)d.width="310";if(typeof d.height==x||!/%$/.test(d.height)&&parseInt(d.height,10)<137)d.height="137";o.title=o.title.slice(0,47)+" - Flash Player Installation";k=m.ie&&m.win?"ActiveX":"PlugIn";k="MMredirectURL="+E.location.toString().replace(/&/g,"%26")+"&MMplayerType="+k+"&MMdoctitle="+o.title;if(typeof f.flashvars!=x)f.flashvars+="&"+k;else f.flashvars=
k;if(m.ie&&m.win&&l.readyState!=4){k=o.createElement("div");h+="SWFObjectNew";k.setAttribute("id",h);l.parentNode.insertBefore(k,l);l.style.display="none";(function(){l.readyState==4?l.parentNode.removeChild(l):setTimeout(arguments.callee,10)})()}p(d,f,h)}}function n(d){if(m.ie&&m.win&&d.readyState!=4){var f=o.createElement("div");d.parentNode.insertBefore(f,d);f.parentNode.replaceChild(j(d),f);d.style.display="none";(function(){d.readyState==4?d.parentNode.removeChild(d):setTimeout(arguments.callee,
10)})()}else d.parentNode.replaceChild(j(d),d)}function j(d){var f=o.createElement("div");if(m.win&&m.ie)f.innerHTML=d.innerHTML;else if(d=d.getElementsByTagName(F)[0])if(d=d.childNodes)for(var h=d.length,k=0;k<h;k++)!(d[k].nodeType==1&&d[k].nodeName=="PARAM")&&d[k].nodeType!=8&&f.appendChild(d[k].cloneNode(true));return f}function p(d,f,h){var k,l=v(h);if(m.wk&&m.wk<312)return k;if(l){if(typeof d.id==x)d.id=h;if(m.ie&&m.win){var r="";for(var q in d)if(d[q]!=Object.prototype[q])if(q.toLowerCase()==
"data")f.movie=d[q];else if(q.toLowerCase()=="styleclass")r+=' class="'+d[q]+'"';else if(q.toLowerCase()!="classid")r+=" "+q+'="'+d[q]+'"';q="";for(var z in f)if(f[z]!=Object.prototype[z])q+='<param name="'+z+'" value="'+f[z]+'" />';l.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+r+">"+q+"</object>";T[T.length]=d.id;k=v(d.id)}else{z=o.createElement(F);z.setAttribute("type",Q);for(var A in d)if(d[A]!=Object.prototype[A])if(A.toLowerCase()=="styleclass")z.setAttribute("class",
d[A]);else A.toLowerCase()!="classid"&&z.setAttribute(A,d[A]);for(r in f)if(f[r]!=Object.prototype[r]&&r.toLowerCase()!="movie"){d=z;q=r;A=f[r];h=o.createElement("param");h.setAttribute("name",q);h.setAttribute("value",A);d.appendChild(h)}l.parentNode.replaceChild(z,l);k=z}}return k}function u(d){var f=v(d);if(f&&f.nodeName=="OBJECT")if(m.ie&&m.win){f.style.display="none";(function(){if(f.readyState==4){var h=v(d);if(h){for(var k in h)if(typeof h[k]=="function")h[k]=null;h.parentNode.removeChild(h)}}else setTimeout(arguments.callee,
10)})()}else f.parentNode.removeChild(f)}function v(d){var f=null;try{f=o.getElementById(d)}catch(h){}return f}function B(d,f,h){d.attachEvent(f,h);M[M.length]=[d,f,h]}function D(d){var f=m.pv;d=d.split(".");d[0]=parseInt(d[0],10);d[1]=parseInt(d[1],10)||0;d[2]=parseInt(d[2],10)||0;return f[0]>d[0]||f[0]==d[0]&&f[1]>d[1]||f[0]==d[0]&&f[1]==d[1]&&f[2]>=d[2]?true:false}function C(d,f,h,k){if(!(m.ie&&m.mac)){var l=o.getElementsByTagName("head")[0];if(l){h=h&&typeof h=="string"?h:"screen";if(k)Y=G=null;
if(!G||Y!=h){k=o.createElement("style");k.setAttribute("type","text/css");k.setAttribute("media",h);G=l.appendChild(k);if(m.ie&&m.win&&typeof o.styleSheets!=x&&o.styleSheets.length>0)G=o.styleSheets[o.styleSheets.length-1];Y=h}if(m.ie&&m.win)G&&typeof G.addRule==F&&G.addRule(d,f);else G&&typeof o.createTextNode!=x&&G.appendChild(o.createTextNode(d+" {"+f+"}"))}}}function y(d,f){if(aa){var h=f?"visible":"hidden";if(L&&v(d))v(d).style.visibility=h;else C("#"+d,"visibility:"+h)}}function s(d){return/[\\\"<>\.;]/.exec(d)!=
null&&typeof encodeURIComponent!=x?encodeURIComponent(d):d}var x="undefined",F="object",Q="application/x-shockwave-flash",$="SWFObjectExprInst",E=window,o=document,J=navigator,ba=false,P=[function(){ba?e():g()}],I=[],T=[],M=[],N,S,X,Z,L=false,R=false,G,Y,aa=true,m=function(){var d=typeof o.getElementById!=x&&typeof o.getElementsByTagName!=x&&typeof o.createElement!=x,f=J.userAgent.toLowerCase(),h=J.platform.toLowerCase(),k=h?/win/.test(h):/win/.test(f);h=h?/mac/.test(h):/mac/.test(f);f=/webkit/.test(f)?
parseFloat(f.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;var l=!+"\u000b1",r=[0,0,0],q=null;if(typeof J.plugins!=x&&typeof J.plugins["Shockwave Flash"]==F){if((q=J.plugins["Shockwave Flash"].description)&&!(typeof J.mimeTypes!=x&&J.mimeTypes[Q]&&!J.mimeTypes[Q].enabledPlugin)){ba=true;l=false;q=q.replace(/^.*\s+(\S+\s+\S+$)/,"$1");r[0]=parseInt(q.replace(/^(.*)\..*$/,"$1"),10);r[1]=parseInt(q.replace(/^.*\.(.*)\s.*$/,"$1"),10);r[2]=/[a-zA-Z]/.test(q)?parseInt(q.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0}}else if(typeof E.ActiveXObject!=x)try{var z=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(z)if(q=z.GetVariable("$version")){l=true;q=q.split(" ")[1].split(",");r=[parseInt(q[0],10),parseInt(q[1],10),parseInt(q[2],10)]}}catch(A){}return{w3:d,pv:r,wk:f,ie:l,win:k,mac:h}}();(function(){if(m.w3){if(typeof o.readyState!=x&&o.readyState=="complete"||typeof o.readyState==x&&(o.getElementsByTagName("body")[0]||o.body))a();if(!L){typeof o.addEventListener!=x&&o.addEventListener("DOMContentLoaded",
a,false);if(m.ie&&m.win){o.attachEvent("onreadystatechange",function(){if(o.readyState=="complete"){o.detachEvent("onreadystatechange",arguments.callee);a()}});E==top&&function(){if(!L){try{o.documentElement.doScroll("left")}catch(d){setTimeout(arguments.callee,0);return}a()}}()}m.wk&&function(){L||(/loaded|complete/.test(o.readyState)?a():setTimeout(arguments.callee,0))}();c(a)}}})();(function(){m.ie&&m.win&&window.attachEvent("onunload",function(){for(var d=M.length,f=0;f<d;f++)M[f][0].detachEvent(M[f][1],
M[f][2]);d=T.length;for(f=0;f<d;f++)u(T[f]);for(var h in m)m[h]=null;m=null;for(var k in swfobject)swfobject[k]=null;swfobject=null})})();return{registerObject:function(d,f,h,k){if(m.w3&&d&&f){var l={};l.id=d;l.swfVersion=f;l.expressInstall=h;l.callbackFn=k;I[I.length]=l;y(d,false)}else k&&k({success:false,id:d})},getObjectById:function(d){if(m.w3)return i(d)},embedSWF:function(d,f,h,k,l,r,q,z,A,O){var U={success:false,id:f};if(m.w3&&!(m.wk&&m.wk<312)&&d&&f&&h&&k&&l){y(f,false);b(function(){h+="";
k+="";var K={};if(A&&typeof A===F)for(var H in A)K[H]=A[H];K.data=d;K.width=h;K.height=k;H={};if(z&&typeof z===F)for(var V in z)H[V]=z[V];if(q&&typeof q===F)for(var W in q)if(typeof H.flashvars!=x)H.flashvars+="&"+W+"="+q[W];else H.flashvars=W+"="+q[W];if(D(l)){V=p(K,H,f);K.id==f&&y(f,true);U.success=true;U.ref=V}else if(r&&t()){K.data=r;w(K,H,f,O);return}else y(f,true);O&&O(U)})}else O&&O(U)},switchOffAutoHideShow:function(){aa=false},ua:m,getFlashPlayerVersion:function(){return{major:m.pv[0],minor:m.pv[1],
release:m.pv[2]}},hasFlashPlayerVersion:D,createSWF:function(d,f,h){if(m.w3)return p(d,f,h)},showExpressInstall:function(d,f,h,k){m.w3&&t()&&w(d,f,h,k)},removeSWF:function(d){m.w3&&u(d)},createCSS:function(d,f,h,k){m.w3&&C(d,f,h,k)},addDomLoadEvent:b,addLoadEvent:c,getQueryParamValue:function(d){var f=o.location.search||o.location.hash;if(f){if(/\?/.test(f))f=f.split("?")[1];if(d==null)return s(f);f=f.split("&");for(var h=0;h<f.length;h++)if(f[h].substring(0,f[h].indexOf("="))==d)return s(f[h].substring(f[h].indexOf("=")+
1))}return""},expressInstallCallback:function(){if(R){var d=v($);if(d&&N){d.parentNode.replaceChild(N,d);if(S){y(S,true);if(m.ie&&m.win)N.style.display="block"}X&&X(Z)}R=false}}}}();function FABridge(a,b){this.target=a;this.remoteTypeCache={};this.remoteInstanceCache={};this.remoteFunctionCache={};this.localFunctionCache={};this.bridgeID=FABridge.nextBridgeID++;this.name=b;this.nextLocalFuncID=0;FABridge.instances[this.name]=this;FABridge.idMap[this.bridgeID]=this;return this}
FABridge.TYPE_ASINSTANCE=1;FABridge.TYPE_ASFUNCTION=2;FABridge.TYPE_JSFUNCTION=3;FABridge.TYPE_ANONYMOUS=4;FABridge.initCallbacks={};FABridge.userTypes={};FABridge.addToUserTypes=function(){for(var a=0;a<arguments.length;a++)FABridge.userTypes[arguments[a]]={typeName:arguments[a],enriched:false}};FABridge.argsToArray=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b};function instanceFactory(a){this.fb_instance_id=a;return this}
function FABridge__invokeJSFunction(a){var b=a[0];a=a.concat();a.shift();return FABridge.extractBridgeFromID(b).invokeLocalFunction(b,a)}FABridge.addInitializationCallback=function(a,b){var c=FABridge.instances[a];if(c!=undefined)b.call(c);else{c=FABridge.initCallbacks[a];if(c==null)FABridge.initCallbacks[a]=c=[];c.push(b)}};
function FABridge__bridgeInitialized(a){var b=document.getElementsByTagName("object"),c=b.length,e=[];if(c>0)for(var g=0;g<c;g++)if(typeof b[g].SetVariable!="undefined")e[e.length]=b[g];c=document.getElementsByTagName("embed");g=c.length;b=[];if(g>0)for(var i=0;i<g;i++)if(typeof c[i].SetVariable!="undefined")b[b.length]=c[i];i=e.length;c=b.length;g="bridgeName="+a;if(i==1&&!c||i==1&&c==1)FABridge.attachBridge(e[0],a);else if(c==1&&!i)FABridge.attachBridge(b[0],a);else{var t=false;if(i>1)for(var w=
0;w<i;w++){for(var n=e[w].childNodes,j=0;j<n.length;j++){var p=n[j];if(p.nodeType==1&&p.tagName.toLowerCase()=="param"&&p.name.toLowerCase()=="flashvars"&&p.value.indexOf(g)>=0){FABridge.attachBridge(e[w],a);t=true;break}}if(t)break}if(!t&&c>1)for(e=0;e<c;e++)if(b[e].attributes.getNamedItem("flashVars").nodeValue.indexOf(g)>=0){FABridge.attachBridge(b[e],a);break}}return true}FABridge.nextBridgeID=0;FABridge.instances={};FABridge.idMap={};FABridge.refCount=0;
FABridge.extractBridgeFromID=function(a){return FABridge.idMap[a>>16]};FABridge.attachBridge=function(a,b){var c=new FABridge(a,b);FABridge[b]=c;var e=FABridge.initCallbacks[b];if(e!=null){for(var g=0;g<e.length;g++)e[g].call(c);delete FABridge.initCallbacks[b]}};FABridge.blockedMethods={toString:true,get:true,set:true,call:true};
FABridge.prototype={root:function(){return this.deserialize(this.target.getRoot())},releaseASObjects:function(){return this.target.releaseASObjects()},releaseNamedASObject:function(a){return typeof a!="object"?false:this.target.releaseNamedASObject(a.fb_instance_id)},create:function(a){return this.deserialize(this.target.create(a))},makeID:function(a){return(this.bridgeID<<16)+a},getPropertyFromAS:function(a,b){if(FABridge.refCount>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{FABridge.refCount++;retVal=this.target.getPropFromAS(a,b);retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},setPropertyInAS:function(a,b,c){if(FABridge.refCount>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{FABridge.refCount++;retVal=this.target.setPropInAS(a,b,this.serialize(c));retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},
callASFunction:function(a,b){if(FABridge.refCount>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{FABridge.refCount++;retVal=this.target.invokeASFunction(a,this.serialize(b));retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},callASMethod:function(a,b,c){if(FABridge.refCount>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{FABridge.refCount++;c=this.serialize(c);retVal=this.target.invokeASMethod(a,b,c);retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},invokeLocalFunction:function(a,b){var c,e=this.localFunctionCache[a];if(e!=undefined)c=this.serialize(e.apply(null,this.deserialize(b)));return c},getTypeFromName:function(a){return this.remoteTypeCache[a]},createProxy:function(a,b){var c=this.getTypeFromName(b);instanceFactory.prototype=c;c=new instanceFactory(a);return this.remoteInstanceCache[a]=
c},getProxy:function(a){return this.remoteInstanceCache[a]},addTypeDataToCache:function(a){newType=new ASProxy(this,a.name);for(var b=a.accessors,c=0;c<b.length;c++)this.addPropertyToType(newType,b[c]);a=a.methods;for(c=0;c<a.length;c++)FABridge.blockedMethods[a[c]]==undefined&&this.addMethodToType(newType,a[c]);return this.remoteTypeCache[newType.typeName]=newType},addPropertyToType:function(a,b){var c=b.charAt(0),e;if(c>="a"&&c<="z"){e="get"+c.toUpperCase()+b.substr(1);c="set"+c.toUpperCase()+b.substr(1)}else{e=
"get"+b;c="set"+b}a[c]=function(g){this.bridge.setPropertyInAS(this.fb_instance_id,b,g)};a[e]=function(){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,b))}},addMethodToType:function(a,b){a[b]=function(){return this.bridge.deserialize(this.bridge.callASMethod(this.fb_instance_id,b,FABridge.argsToArray(arguments)))}},getFunctionProxy:function(a){var b=this;if(this.remoteFunctionCache[a]==null)this.remoteFunctionCache[a]=function(){b.callASFunction(a,FABridge.argsToArray(arguments))};
return this.remoteFunctionCache[a]},getFunctionID:function(a){if(a.__bridge_id__==undefined){a.__bridge_id__=this.makeID(this.nextLocalFuncID++);this.localFunctionCache[a.__bridge_id__]=a}return a.__bridge_id__},serialize:function(a){var b={},c=typeof a;if(c=="number"||c=="string"||c=="boolean"||c==null||c==undefined)b=a;else if(a instanceof Array){b=[];for(c=0;c<a.length;c++)b[c]=this.serialize(a[c])}else if(c=="function"){b.type=FABridge.TYPE_JSFUNCTION;b.value=this.getFunctionID(a)}else if(a instanceof
ASProxy){b.type=FABridge.TYPE_ASINSTANCE;b.value=a.fb_instance_id}else{b.type=FABridge.TYPE_ANONYMOUS;b.value=a}return b},deserialize:function(a){var b,c=typeof a;if(c=="number"||c=="string"||c=="boolean"||a==null||a==undefined)b=this.handleError(a);else if(a instanceof Array){b=[];for(c=0;c<a.length;c++)b[c]=this.deserialize(a[c])}else if(c=="object"){for(c=0;c<a.newTypes.length;c++)this.addTypeDataToCache(a.newTypes[c]);for(var e in a.newRefs)this.createProxy(e,a.newRefs[e]);if(a.type==FABridge.TYPE_PRIMITIVE)b=
a.value;else if(a.type==FABridge.TYPE_ASFUNCTION)b=this.getFunctionProxy(a.value);else if(a.type==FABridge.TYPE_ASINSTANCE)b=this.getProxy(a.value);else if(a.type==FABridge.TYPE_ANONYMOUS)b=a.value}return b},addRef:function(a){this.target.incRef(a.fb_instance_id)},release:function(a){this.target.releaseRef(a.fb_instance_id)},handleError:function(a){if(typeof a=="string"&&a.indexOf("__FLASHERROR")==0){a=a.split("||");FABridge.refCount>0&&FABridge.refCount--;throw Error(a[1]);}return a}};
ASProxy=function(a,b){this.bridge=a;this.typeName=b;return this};ASProxy.prototype={get:function(a){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,a))},set:function(a,b){this.bridge.setPropertyInAS(this.fb_instance_id,a,b)},call:function(a,b){this.bridge.callASMethod(this.fb_instance_id,a,b)},addRef:function(){this.bridge.addRef(this)},release:function(){this.bridge.release(this)}};
(function(){function a(e,g){return function(i){var t=new b;t.initEvent(g,true,true);t.target=t.currentTarget=e;for(var w in i)t[w]=i[w];e.dispatchEvent(t,arguments)}}function b(){}if(!window.WebSocket){var c=window.console;c||(c={log:function(){},error:function(){}});if(function(){if("navigator"in window&&"plugins"in navigator&&navigator.plugins["Shockwave Flash"])return!!navigator.plugins["Shockwave Flash"].description;if("ActiveXObject"in window)try{return!!(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")}catch(e){}return false}()){WebSocket=
function(e,g,i,t,w){var n=this;n.readyState=WebSocket.CONNECTING;n.bufferedAmount=0;WebSocket.__addTask(function(){n.__flash=WebSocket.__flash.create(e,g,i||null,t||0,w||null);n.__flash.addEventListener("open",function(){try{n.onopen&&n.onopen()}catch(j){c.error(j.toString())}});n.__flash.addEventListener("close",function(){try{n.onclose&&n.onclose()}catch(j){c.error(j.toString())}});n.__flash.addEventListener("message",function(j){j=decodeURIComponent(j.getData());try{if(n.onmessage){var p;if(window.MessageEvent){p=
document.createEvent("MessageEvent");p.initMessageEvent("message",false,false,j,null,null,window)}else p={data:j};n.onmessage(p)}}catch(u){c.error(u.toString())}});n.__flash.addEventListener("stateChange",function(j){try{n.readyState=j.getReadyState();n.bufferedAmount=j.getBufferedAmount()}catch(p){c.error(p.toString())}})})};WebSocket.prototype.send=function(e){if(!this.__flash||this.readyState==WebSocket.CONNECTING)throw"INVALID_STATE_ERR: Web Socket connection has not been established";e=this.__flash.send(e);
if(e<0)return true;else{this.bufferedAmount=e;return false}};WebSocket.prototype.close=function(){if(this.__flash)if(this.readyState==WebSocket.OPEN){this.__flash.close();this.readyState=WebSocket.CLOSED;this.onclose&&this.onclose()}};WebSocket.prototype.addEventListener=function(e,g){if(!("__events"in this))this.__events={};if(!(e in this.__events)){this.__events[e]=[];if("function"==typeof this["on"+e]){this.__events[e].defaultHandler=this["on"+e];this["on"+e]=a(this,e)}}this.__events[e].push(g)};
WebSocket.prototype.removeEventListener=function(e,g){if(!("__events"in this))this.__events={};if(e in this.__events)for(var i=this.__events.length;i>-1;--i)if(g===this.__events[e][i]){this.__events[e].splice(i,1);break}};WebSocket.prototype.dispatchEvent=function(e){if(!("__events"in this))throw"UNSPECIFIED_EVENT_TYPE_ERR";if(!(e.type in this.__events))throw"UNSPECIFIED_EVENT_TYPE_ERR";for(var g=0,i=this.__events[e.type].length;g<i;++g){this.__events[e.type][g](e);if(e.cancelBubble)break}false!==
e.returnValue&&"function"==typeof this.__events[e.type].defaultHandler&&this.__events[e.type].defaultHandler(e)};b.prototype.cancelable=true;b.prototype.cancelBubble=false;b.prototype.preventDefault=function(){if(this.cancelable)this.returnValue=false};b.prototype.stopPropagation=function(){this.cancelBubble=true};b.prototype.initEvent=function(e,g,i){this.type=e;this.cancelable=i;this.timeStamp=new Date};WebSocket.CONNECTING=0;WebSocket.OPEN=1;WebSocket.CLOSED=2;WebSocket.__tasks=[];WebSocket.__initialize=
function(){if(WebSocket.__swfLocation){var e=document.createElement("div");e.id="webSocketContainer";e.style.position="absolute";e.style.left="-100px";e.style.top="-100px";var g=document.createElement("div");g.id="webSocketFlash";e.appendChild(g);document.body.appendChild(e);swfobject.embedSWF(WebSocket.__swfLocation,"webSocketFlash","8","8","9.0.0",null,{bridgeName:"webSocket"},null,null,function(i){i.success||c.error("[WebSocket] swfobject.embedSWF failed")});FABridge.addInitializationCallback("webSocket",
function(){try{WebSocket.__flash=FABridge.webSocket.root();WebSocket.__flash.setCallerUrl(location.href);for(var i=0;i<WebSocket.__tasks.length;++i)WebSocket.__tasks[i]();WebSocket.__tasks=[]}catch(t){c.error("[WebSocket] "+t.toString())}})}else c.error("[WebSocket] set WebSocket.__swfLocation to location of WebSocketMain.swf")};WebSocket.__addTask=function(e){WebSocket.__flash?e():WebSocket.__tasks.push(e)};window.addEventListener?window.addEventListener("load",WebSocket.__initialize,false):window.attachEvent("onload",
WebSocket.__initialize)}else c.error("Flash Player is not installed.")}})();